### ISSUE TITLE
Add NCA parameters to `calc_derived`

### ISSUE THREAD

**Issue by billdenney** [cran/pmxTools#1]
What do you think about adding NCA parameters to the outputs of `calc_derived*()`?

The specific parameters I'm thinking of are:

* Cmax_dose_normalized
* Tmax
* AUC_dose_normalized (AUCinf for single dose and AUCtau for steady-state)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by billdenney** [comment]
Whoops!  Thanks.
